# Generated by Django 6.0.6 on 2026-06-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_taskattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
